using System.Collections;
using System.Collections.Generic;
using UnityEngine;

/*
 * This class describes the behavior of the shield generated by the Angel 
 */

public class AngelScoutBehavior : MonoBehaviour
{
    // the shield is active just for 10 seconds
    private float life = 10;

    // this variable is not important - is used just to solve a bug
    public bool original = true;

    // the angel that is attached to the shield for design purpose
    public GameObject angel;

    // Start is called before the first frame update
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        if (!original)
        {
            if (life <= 0)
            {
                Destroy(gameObject);
                Destroy(angel);
            }

            life -= Time.deltaTime;
        }
    }

}
